{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.component }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{.Values.component}}.rdevopsb72.online
    http:
      paths:
      - backend:
          service:
            name: {{.Values.component}}
            port:
              number: {{.Values.port}}
        path: /
        pathType: Prefix
{{- end }}
